## Create User

POST http://localhost:3005/v1/notifications
Content-Type: application/json

{
  "recipientId": "1b327ed1-a2bc-4cce-9d37-38a8964ce0ed",
  "title": "Login Social",
  "content": "some content"
}

###
PATCH  http://localhost:3005/v1/notifications/1bd897e7-a9c2-4da5-b4ff-3e85f2520809/read/1b327ed1-a2bc-4cce-9d37-38a8964ce0ed
Content-Type: application/json

###
GET   http://localhost:3005/v1/notifications/1b327ed1-a2bc-4cce-9d37-38a8964ce0ed?perPage=2&page=1
Content-Type: application/json