## Create User

POST http://localhost:3005/v1/notifications
Content-Type: application/json

{
  "recipientId": "1b327ed1-a2bc-4cce-9d37-38a8964ce0ed",
  "title": "some title",
  "content": "some content"
}

###
PATCH  http://localhost:3005/v1/notifications/a93af6c5-af1f-4148-b878-7c4218204cc/read/1b327ed1-a2bc-4cce-9d37-38a8964ce0ed
Content-Type: application/json

###
GET   http://localhost:3005/v1/notifications/1b327ed1-a2bc-4cce-9d37-38a8964ce0ed?perPage=2&page=1
Content-Type: application/json