version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    container_name: micro-notification-api
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/node/app
    depends_on:
      - mongodb

  mongodb:
    container_name: micro-notification-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_ROOT_USERNAME: admin
      MONGO_ROOT_PASSWORD: admin
      MONGO_DATABASE: micro-notification-mongodb
