version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    container_name: micro-notification-api
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/node/app
    depends_on:
      - mongodb

  mongodb:
    container_name: micro-notification-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_ROOT_USERNAME: admin
      MONGO_ROOT_PASSWORD: admin
      MONGO_DATABASE: micro-notification-mongodb

  rabbitmq:
    image: "rabbitmq:3.8-management"
    container_name: "micro-notification-rabbitmq"
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  rabbitmq_data:
    driver: local
